### ISSUE TITLE
Petrolium Production is lagging behind

### ISSUE THREAD

**Issue by spight-zz** [zippydaspinhead/Italian-Cooking#1]
The current generation of petroleum, which was sufficient originally, is now outdated, and much like Qonos, we're pretending it's not part of first gen, but it is. 

Let's figure out how fast the crude oil train runs a circuit and scale up oil refining to match it. This time, we need to use water instead of pure crude oil to produce a higher percentage of usable petroleum

**Comment by zippydaspinhead** [comment]
Not sure the circuit takes much time.

Current pumpjack setup in the pickup-station fills a 4 car train in just a few seconds.  This may change as the wells start to dry up, but I think converting to water/oil refining should occur first to see demand and scale accordingly.  Return trip with current 410 loop setup takes roughly 30 seconds depending on bottlenecks/other trains.

**Comment by zippydaspinhead** [comment]
Should be roughly 300K crude per trip.

**Comment by spight-zz** [comment]
With 4 tanks, it brings 100k per trip. Tanks no longer store 75k

**Comment by zippydaspinhead** [comment]
Was unaware of this change.

In that case the pickup-station's throughput is much higher than the train itself, as it was built to transfer 300K quickly.  If crude throughput is an issue, recommend adding an additional train(s) to the route.  Station should be able to easily handle 2-3 additional trains without slowing down the pickup.

**Comment by spight-zz** [comment]
Doing some napkin math, I'm finding the following numbers necessary to manage 100k crude oil per minute:

* 84 Oil Refineries (Advanced Oil Processing)
* 12 Chemical Plants (Cracking Heavy Oil)
* 12 Chemical Plants (Cracking Light Oil)
* 1 Offshore pump
This will produce 60k petroleum oil per minute

**Comment by zippydaspinhead** [comment]
Old map, closing.
