### ISSUE TITLE
410 Loop Needs converting to true double rail system

### ISSUE THREAD

**Issue by zippydaspinhead** [zippydaspinhead/Italian-Cooking#3]
410 is currently a mismash of single rail, bypasses, stations, and more than one bottleneck.  Propose updating/replacing rail system with double rail system to match 1604 and the rest of the rail network.

**Comment by spight-zz** [comment]
I think with the end of the game so nearby, this undertaking will be too much work for its benefit.

This issue might be solvable by reducing the number of trains that run plastic by changing from a pull system with four trains to a push system with a single train. Additionally, we might consider creating a dedicated line for crude oil delivery so it doesn't get slowed down when plastic runs low, creating an unstable system

**Comment by zippydaspinhead** [comment]
Old map, closing
